before:
  hooks:
    - go mod download
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
brews:
  - name: vssh
    github:
      owner: jmgilman
      name: brew
    commit_author:
      name: Joshua Gilman
      email: joshuagilman@gmail.com
    folder: Formula
    homepage: "https://github.com/jmgilman/vssh"
    description: "A small CLI wrapper for authenticating with SSH keys from Hashicorp Vault"
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
